version: "3.8"

services:
  webapp:
    build:
      context: .
      target: nextjs-app
    ports:
      - "3000:3000"
    environment:
      API_URL: $API_URL
      GOV_NOTIFY_CUSTOMER_EMAIL_TEMPLATE: $GOV_NOTIFY_CUSTOMER_EMAIL_TEMPLATE
      GOV_NOTIFY_API_KEY: $GOV_NOTIFY_API_KEY
      BASIC_AUTH: $BASIC_AUTH
